import { useEffect, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle2, Clock3, Globe2, Radar, ScanSearch } from 'lucide-react';
import { Link, useOutletContext } from 'react-router-dom';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import Header from '../components/Header';
import StatCard from '../components/StatCard';
import EmptyState from '../components/EmptyState';
import ChangeBadge from '../components/ChangeBadge';
import StatusBadge from '../components/StatusBadge';
import { SkeletonCards } from '../components/Loading';
import SiteFormModal from '../components/SiteFormModal';
import api, { apiError } from '../services/api';
import { useToast } from '../context/ToastContext';
import { formatDate } from '../utils/format';

export default function Dashboard() {
  const { openMenu } = useOutletContext(); const { toast } = useToast();
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [busy, setBusy] = useState(false);
  async function load() { setLoading(true); try { const res = await api.get('/api/dashboard'); setData(res.data.data); } catch(e){ toast(apiError(e),'error'); } finally { setLoading(false); } }
  useEffect(()=>{ load(); },[]);
  async function addSite(form){setBusy(true);try{await api.post('/api/sites',form);toast('Website added.');setModal(false);await load();}catch(e){toast(apiError(e),'error')}finally{setBusy(false)}}
  const stats = data?.stats || {};
  return <><Header title="Website Intelligence" subtitle="Monitor what matters across the web." onMenu={openMenu} primaryAction={{label:'Add website',onClick:()=>setModal(true)}}/><div className="page-content">
    {loading ? <SkeletonCards count={7}/> : <div className="stats-grid"><StatCard icon={Globe2} label="Websites monitored" value={stats.websitesMonitored}/><StatCard icon={ScanSearch} label="Scans performed" value={stats.scansPerformed}/><StatCard icon={Activity} label="Changes detected" value={stats.changesDetected}/><StatCard icon={AlertTriangle} label="Critical changes" value={stats.criticalChanges}/><StatCard icon={CheckCircle2} label="Websites online" value={stats.websitesOnline}/><StatCard icon={AlertTriangle} label="Websites offline" value={stats.websitesOffline}/><StatCard icon={Clock3} label="Last scan" value={formatDate(stats.lastScan)}/></div>}
    {!loading && (!stats.websitesMonitored ? <EmptyState action={<button className="btn btn-primary" onClick={()=>setModal(true)}>Add Website</button>}/> : <>
      <div className="dashboard-grid"><section className="panel chart-panel"><div className="panel-head"><div><h2>Monitoring activity</h2><p>Recent scans and detected changes</p></div><span className="panel-kicker">Last 14 active days</span></div><div className="chart-wrap">{data?.trend?.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={data.trend}><defs><linearGradient id="areaScan" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="currentColor" stopOpacity={0.25}/><stop offset="95%" stopColor="currentColor" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={(x)=>x.slice(5)} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="scans" stroke="currentColor" fill="url(#areaScan)" strokeWidth={2}/><Area type="monotone" dataKey="changes" stroke="#f97316" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer> : <div className="chart-empty">Run a few scans to build your trend.</div>}</div></section>
      <section className="panel"><div className="panel-head"><div><h2>Recent changes</h2><p>Latest monitoring events</p></div><Link to="/dashboard/activity">View all</Link></div><div className="activity-list">{data?.recentActivity?.slice(0,6).map(item=><Link to={`/dashboard/sites/${item.siteId}/scans/${item.id}`} className="activity-row" key={`${item.siteId}-${item.id}`}><div className="activity-dot"><Radar size={17}/></div><div className="activity-copy"><strong>{item.siteName}</strong><span>{item.changed ? item.changes?.[0]?.label || 'Website changed' : 'Scan completed — no significant changes'}</span><small>{formatDate(item.createdAt)}</small></div><ChangeBadge severity={item.severity} score={item.changeScore}/></Link>)}</div></section></div>
      <section className="panel monitored-panel"><div className="panel-head"><div><h2>Monitored websites</h2><p>Your latest website status</p></div><Link to="/dashboard/sites">Manage websites</Link></div><div className="simple-table"><div className="table-head"><span>Website</span><span>Status</span><span>Last change</span><span>Scans</span><span>Last scan</span></div>{data?.sites?.map(site=><Link className="table-row" to={`/dashboard/sites/${site.id}`} key={site.id}><span><strong>{site.name}</strong><small>{site.category}</small></span><span><StatusBadge status={site.lastStatus}/></span><span><ChangeBadge severity={site.lastSeverity} score={site.lastChangeScore}/></span><span>{site.totalScans||0}</span><span>{formatDate(site.lastScanAt)}</span></Link>)}</div></section>
      <section className="analytics-section"><div className="section-row-title"><div><h2>Analytics</h2><p>Changes, scans, severity, category, and website health</p></div></div><div className="analytics-grid"><div className="panel mini-chart-panel"><div className="panel-head"><div><h2>Changes by website</h2><p>Top monitored sites</p></div></div><div className="mini-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data?.analytics?.byWebsite||[]}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" hide/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="changes" fill="#5b5bd6" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="panel mini-chart-panel"><div className="panel-head"><div><h2>Changes by category</h2><p>Where activity is concentrated</p></div></div><div className="mini-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data?.analytics?.byCategory||[]}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:9}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="changes" fill="#7c7ce8" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="panel mini-chart-panel"><div className="panel-head"><div><h2>Change severity</h2><p>Recent scan distribution</p></div></div><div className="mini-chart pie-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={(data?.analytics?.severity||[]).filter(x=>x.value>0)} dataKey="value" nameKey="name" innerRadius={48} outerRadius={72} paddingAngle={3}>{['#94a3b8','#eab308','#f59e0b','#f97316','#dc4c64'].map((color,i)=><Cell key={color} fill={color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></div><div className="panel mini-chart-panel"><div className="panel-head"><div><h2>Website status</h2><p>Current monitoring health</p></div></div><div className="mini-chart pie-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={(data?.analytics?.status||[]).filter(x=>x.value>0)} dataKey="value" nameKey="name" innerRadius={48} outerRadius={72} paddingAngle={3}>{['#20b77a','#dc4c64','#94a3b8'].map(color=><Cell key={color} fill={color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></div></div></section>
    </>)}
  </div><SiteFormModal open={modal} busy={busy} onClose={()=>setModal(false)} onSubmit={addSite}/></>;
}
